--- #YAML:1.0
name:                IP-Country-DNSBL
version:             1.01
abstract:            IP geolocation via DNS
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Net::DNS:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Nigel Wetters Gourlay <nwetters@cpan.org>
